CREATE TABLE IF NOT EXISTS client (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);


CREATE TABLE IF NOT EXISTS module (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);


CREATE TABLE IF NOT EXISTS ticket (
    id BIGSERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    opening_date DATE NOT NULL,
    closing_date DATE NOT NULL,
    fk_id_client INTEGER,
    fk_id_module INTEGER,
    CONSTRAINT fk_ticket_client FOREIGN KEY (fk_id_client) REFERENCES "client" (id),
    CONSTRAINT fk_ticket_module FOREIGN KEY (fk_id_module) REFERENCES "module" (id) 
);

-- INSERT AGORA

INSERT INTO CLIENT (NAME) VALUES('Apple Inc');
INSERT INTO CLIENT (NAME) VALUES('Google');
INSERT INTO CLIENT (NAME) VALUES('Microsoft');
INSERT INTO CLIENT (NAME) VALUES('Tesla');
INSERT INTO CLIENT (NAME) VALUES('SpaceX');

INSERT INTO MODULE (NAME) VALUES('Finaneiro');
INSERT INTO MODULE (NAME) VALUES('Vendas');
INSERT INTO MODULE (NAME) VALUES('Expedição');
INSERT INTO MODULE (NAME) VALUES('Foguetes');

INSERT INTO TICKET (TITLE, FK_ID_CLIENT, OPENING_DATE, CLOSING_DATE, FK_ID_MODULE)
VALUES (TRIM('Mussum Ipsum cacilds vidis litro  '), 1, '2021-03-01', '2021-03-02',
 1);
INSERT INTO TICKET (TITLE, FK_ID_CLIENT, OPENING_DATE, CLOSING_DATE, FK_ID_MODULE)
VALUES (TRIM('Praesent malesuada urna nisi '), 1, '2021-03-01', '2021-03-02',
 1);
INSERT INTO TICKET (TITLE, FK_ID_CLIENT, OPENING_DATE, CLOSING_DATE, FK_ID_MODULE)
VALUES (TRIM('Sapien in monti palavris '), 1, '2021-03-01', '2021-03-02',
 1);
INSERT INTO TICKET (TITLE, FK_ID_CLIENT, OPENING_DATE, CLOSING_DATE, FK_ID_MODULE)
VALUES (TRIM('Aenean aliquam molestie '), 1, '2021-03-01', '2021-03-02',
 1);
INSERT INTO TICKET (TITLE, FK_ID_CLIENT, OPENING_DATE, CLOSING_DATE, FK_ID_MODULE)
VALUES (TRIM('Interessantiss quisso pudia '), 1, '2021-03-01', '2021-03-02',
 1);
INSERT INTO TICKET (TITLE, FK_ID_CLIENT, OPENING_DATE, CLOSING_DATE, FK_ID_MODULE)
VALUES (TRIM('In elementis mé pra quem '), 1, '2021-03-01', '2021-03-02',
 2);

INSERT INTO TICKET (TITLE, FK_ID_CLIENT, OPENING_DATE, CLOSING_DATE, FK_ID_MODULE)
VALUES (TRIM('In elementis mé pra quem '), 1, '2021-05-01', '2021-07-02',
        2);
